//dolina.channel,dolina.hostlink,dolina,dolina.semver,dolina.util,tests.channel,tests.hostlink
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import unit_threaded;

int main(string[] args)
{
    return args.runTests!(
                          "dolina.channel",
                          "dolina.hostlink",
                          "dolina",
                          "dolina.semver",
                          "dolina.util",
                          "tests.channel",
                          "tests.hostlink"
                          );
}
